# Homework 3

## **So now i will do some Data wrangling, lets see if i am able to do it. Actually its the first time using markdown.""

In [13]:
import pandas as pd

df = pd.read_csv(r"/Users/gianluca/Library/Mobile\ Documents/com\~apple\~CloudDocs/Universität/HS\ 26/Python\ Seminar/Homework/Homework-Python/Homework\ 3/disney_plus_shows.csv".replace("\\", ""))
df.head()

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,director,writer,actors,language,country,awards,metascore,imdb_rating,imdb_votes
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",Gil Junger,"Karen McCullah, Kirsten Smith","Heath Ledger, Julia Stiles, Joseph Gordon-Levi...","English, French",USA,2 wins & 13 nominations.,70.0,7.3,"283,945"
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",NaN,NaN,"Josh Brener, Michaela Dietz, Bert Davis, Abiga...",English,"UK, USA, Canada",NaN,NaN,6.2,124
2,tt0115433,101 Dalmatians,An evil high-fashion designer plots to steal D...,movie,G,1996,27 Nov 1996,"November 12, 2019",103 min,"Adventure, Comedy, Crime, Family",Stephen Herek,"Dodie Smith (novel), John Hughes (screenplay)","Glenn Close, Jeff Daniels, Joely Richardson, J...","English, Spanish","USA, UK",Nominated for 1 Golden Globe. Another 3 wins &...,49.0,5.7,"97,785"
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",movie,G,2002,21 Jan 2003,"November 12, 2019",74 min,"Animation, Adventure, Comedy, Family, Musical","Jim Kammerud, Brian Smith","Jim Kammerud (story), Dan Root (story), Garret...","Barry Bostwick, Jason Alexander, Martin Short,...",English,USA,5 wins & 10 nominations.,NaN,5.8,"7,434"
4,tt0211181,102 Dalmatians,Cruella DeVil gets out of prison and goes afte...,movie,G,2000,22 Nov 2000,"November 12, 2019",100 min,"Adventure, Comedy, Family",Kevin Lima,"Dodie Smith (novel), Kristen Buckley (story), ...","Glenn Close, Gérard Depardieu, Ioan Gruffudd, ...",English,"USA, UK",Nominated for 1 Oscar. Another 1 win & 7 nomin...,35.0,4.9,"33,444"

In [15]:
df_copy = df.copy()
movies = df_copy[df_copy["type"] == "movie"]
movies.shape

(680, 19)

In [16]:
movies = movies[["imdb_id", "title", "director", "year", "imdb_rating", "imdb_votes"]]
movies.head()

,imdb_id,title,director,year,imdb_rating,imdb_votes
0,tt0147800,10 Things I Hate About You,Gil Junger,1999,7.3,"283,945"
2,tt0115433,101 Dalmatians,Stephen Herek,1996,5.7,"97,785"
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Jim Kammerud, Brian Smith",2002,5.8,"7,434"
4,tt0211181,102 Dalmatians,Kevin Lima,2000,4.9,"33,444"
5,tt1846442,12 Dates of Christmas,James Hayman,2011,6.3,"4,933"

In [17]:
movies = movies.drop_duplicates()
movies.shape

(680, 6)

In [18]:
movies = movies[movies["director"].notna()]
movies = movies[movies["imdb_rating"].notna()]
movies = movies[movies["imdb_votes"].notna()]
movies.shape

(666, 6)

In [19]:
movies = movies.copy()
movies["imdb_votes"] = movies["imdb_votes"].str.replace(",", "")
movies["imdb_votes"] = movies["imdb_votes"].astype(int)
movies["year"] = movies["year"].astype(int)
movies.dtypes

imdb_id            str
title              str
director           str
year             int64
imdb_rating    float64
imdb_votes       int64
dtype: object

In [20]:
movies = movies[movies["imdb_votes"] >= 150]
movies.shape

(624, 6)

In [21]:
movies = movies.copy()
movies["director"] = movies["director"].str.replace("(co-director)", "")
movies.head()

,imdb_id,title,director,year,imdb_rating,imdb_votes
0,tt0147800,10 Things I Hate About You,Gil Junger,1999,7.3,283945
2,tt0115433,101 Dalmatians,Stephen Herek,1996,5.7,97785
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Jim Kammerud, Brian Smith",2002,5.8,7434
4,tt0211181,102 Dalmatians,Kevin Lima,2000,4.9,33444
5,tt1846442,12 Dates of Christmas,James Hayman,2011,6.3,4933

In [22]:
movies["director"] = movies["director"].str.split(", ")
movies.head()

,imdb_id,title,director,year,imdb_rating,imdb_votes
0,tt0147800,10 Things I Hate About You,[Gil Junger],1999,7.3,283945
2,tt0115433,101 Dalmatians,[Stephen Herek],1996,5.7,97785
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"[Jim Kammerud, Brian Smith]",2002,5.8,7434
4,tt0211181,102 Dalmatians,[Kevin Lima],2000,4.9,33444
5,tt1846442,12 Dates of Christmas,[James Hayman],2011,6.3,4933

In [23]:
movies = movies.explode("director")
movies.shape

(845, 6)

In [24]:
counts = movies["director"].value_counts()
counts

director
Wilfred Jackson      20
Clyde Geronimi       17
Jack Hannah          16
Paul Hoen            15
Jack Kinney          15
                     ..
Charles L. Draper     1
Jim Capobianco        1
Peter DeLuise         1
Steve Rash            1
Jared Bush            1
Name: count, Length: 463, dtype: int64

In [25]:
top_directors = counts[counts >= 4]
movies = movies[movies["director"].isin(top_directors.index)]
movies.shape

(275, 6)